  # Kibana Monitor
  - type: http
    schedule: '@every 1s'  # Check every 1 second
    urls: ["http://10.2.160.71:5601/"]
    name: Kibana
    timeout: 5s

  # phpMyAdmin for WordPress Monitor
  - type: http
    schedule: '@every 1s'  # Check every 1 second
    urls: ["http://10.2.160.71:8081/"]
    name: phpMyAdminWordPress
    timeout: 5s

  # RabbitMQ Monitor
  - type: http
    schedule: '@every 1s'  # Check every 1 second
    urls: ["http://10.2.160.71:15672/"]
    name: RabbitMQMonitor  # Changed name to avoid duplication
    timeout: 5s

  # Logstash1 receive from RabbitMQ to Elasticsearch
  - type: tcp
    schedule: '@every 1s'  # Check every 1 second
    hosts: ["10.2.160.71:5044"]
    name: Logstash5044
    timeout: 5s

  # Logstash2 send from Elasticsearch to RabbitMQ
  - type: tcp
    schedule: '@every 1s'  # Check every 1 second
    hosts: ["10.2.160.71:15044"]
    name: Logstash15044
    timeout: 5s

  # Elasticsearch Monitor
  - type: tcp
    schedule: '@every 1s'  # Check every 1 second
    hosts: ["10.2.160.71:9200"]
    name: Elasticsearch
    timeout: 5s

output.elasticsearch:
  hosts: ["https://10.2.160.71:9200/"]
  username: elastic
  password: student1
  protocol: "https"
  ssl.verification_mode: "none"
