filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'  # Typical path for Docker logs
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: ""
        overwrite_keys: true
        add_error_key: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  protocol: "https"
  ssl.verification_mode: "none"

setup.kibana:
  host: ${KIBANA_HOST}