filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'  # Typical path for Docker logs
  processors:
    - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "student1"
  ssl.verification_mode: "none"  # Disable SSL verification if using self-signed certificates

setup.kibana:
  host: "http://10.2.160.71:5601"

